#!/bin/bash
# @package exadra37-docker-images/dockerize-graphical-user-interface-app-demo
# @link    https://gitlab.com/u/exadra37-docker-images/dockerize-graphical-user-interface-app-demo
# @since   12 March 2017
# @license GPL-3.0
# @author  Exadra37(Paulo Silva) <exadra37ingmailpointcom>
#
# Social Links:
# @link    Auhthor:  https://exadra37.com
# @link    Github:   https://gitlab.com/Exadra37
# @link    Github:   https://github.com/Exadra37
# @link    Linkedin: https://uk.linkedin.com/in/exadra37
# @link    Twitter:  https://twitter.com/Exadra37

set -e

########################################################################################################################
# Variables Defaults
########################################################################################################################

    dgad_root_dir=$(dirname $(readlink -f $0))


########################################################################################################################
# Sourcing
########################################################################################################################

    source "${dgad_root_dir}"/src/dockerize-gui-app-demo.sh


########################################################################################################################
# Execution
########################################################################################################################

    "${@}"
